name: 'Module build trigger'
description: 'Triggers the module build pipeline'

inputs:
  type:
    description: 'The tag/name of the event'
    required: true
  environment:
    description: 'The target environment'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo Im triggering the module pipeline now. yeah!
      shell: bash
    - run: echo type=${{ inputs.type }}
      shell: bash
    - run: echo environment=${{ inputs.environment }}
      shell: bash
    - run: echo repository=${{ github.repository }}
      shell: bash
